Collections:
- Metadata:
    Architecture:
    - SNGAN
  Name: SNGAN
  Paper:
  - https://openreview.net/forum?id=B1QRgziT-
  README: configs/sngan_proj/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SNGAN
  Metadata:
    Training Data: CIFAR
  Name: sngan_proj_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      FID: 9.8203
      IS: 9.6919
      Inplace ReLU: w/o
      Iter: 400000.0
      Log: '[Log]'
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_cifar10_32_lr-2e-4_b64x1_woReLUinplace_is-iter400000_20210709_163823-902ce1ae.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SNGAN
  Metadata:
    Training Data: CIFAR
  Name: sngan_proj_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      FID: 8.1158
      IS: 9.5659
      Inplace ReLU: w/o
      Iter: 490000.0
      Log: '[Log]'
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_cifar10_32_lr-2e-4_b64x1_woReLUinplace_fid-iter490000_20210709_163329-ba0862a0.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SNGAN
  Metadata:
    Training Data: CIFAR
  Name: sngan_proj_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      FID: 8.3462
      IS: 9.5564
      Inplace ReLU: w
      Iter: 490000.0
      Log: '[Log]'
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_cifar10_32_lr-2e-4_b64x1_wReLUinplace_is-iter490000_20210709_202230-cd863c74.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SNGAN
  Metadata:
    Training Data: CIFAR
  Name: sngan_proj_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      FID: 8.3462
      IS: 9.5564
      Inplace ReLU: w
      Iter: 490000.0
      Log: '[Log]'
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_cifar10_32_lr-2e-4-b64x1_wReLUinplace_fid-iter490000_20210709_203038-191b2648.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_128_woReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2.py
  In Collection: SNGAN
  Metadata:
    Training Data: IMAGENET
  Name: sngan_proj_128_woReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2
  Results:
  - Dataset: IMAGENET
    Metrics:
      FID: 33.4682
      IS: 30.0651
      Inplace ReLU: w/o
      Iter: 952000.0
      Log: '[Log]'
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_imagenet1k_128_Glr2e-4_Dlr5e-5_ndisc5_b128x2_woReLUinplace_is-iter952000_20210730_132027-9c884a21.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_128_woReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2.py
  In Collection: SNGAN
  Metadata:
    Training Data: IMAGENET
  Name: sngan_proj_128_woReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2
  Results:
  - Dataset: IMAGENET
    Metrics:
      FID: 32.6193
      IS: 29.5779
      Inplace ReLU: w/o
      Iter: 989000.0
      Log: '[Log]'
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_imagenet1k_128_Glr2e-4_Dlr5e-5_ndisc5_b128x2_woReLUinplace_fid-iter988000_20210730_131424-061bf803.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_128_wReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2.py
  In Collection: SNGAN
  Metadata:
    Training Data: IMAGENET
  Name: sngan_proj_128_wReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2
  Results:
  - Dataset: IMAGENET
    Metrics:
      FID: 34.3383
      IS: 28.1799
      Inplace ReLU: w
      Iter: 944000.0
      Log: '[Log]'
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_imagenet1k_128_Glr2e-4_Dlr5e-5_ndisc5_b128x2_wReLUinplace_is-iter944000_20210730_132714-ca0ccd07.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_128_wReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2.py
  In Collection: SNGAN
  Metadata:
    Training Data: IMAGENET
  Name: sngan_proj_128_wReLUinplace_Glr-2e-4_Dlr-5e-5_ndisc5_imagenet1k_b128x2
  Results:
  - Dataset: IMAGENET
    Metrics:
      FID: 33.4821
      IS: 27.7948
      Inplace ReLU: w
      Iter: 988000.0
      Log: '[Log]'
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_proj_imagenet1k_128_Glr2e-4_Dlr5e-5_ndisc5_b128x2_wReLUinplace_fid-iter988000_20210730_132401-9a682411.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_32_cvt_studioGAN.py
  In Collection: SNGAN
  Metadata:
    Training Data: Others
  Name: sngan_proj_32_cvt_studioGAN
  Results:
  - Dataset: Others
    Metrics:
      FID (Our Pipeline): 10.2011
      FID (StudioGAN): 13.248
      IS (Our Pipeline): 9.372
      IS (StudioGAN): 8.677
      Inplace ReLU: w
      Total Iters: 100000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_cifar10_convert-studio-rgb_20210709_111346-2979202d.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj/sngan_proj_32_cvt_studioGAN.py
  In Collection: SNGAN
  Metadata:
    Training Data: Others
  Name: sngan_proj_32_cvt_studioGAN
  Results:
  - Dataset: Others
    Metrics:
      FID (Our Pipeline): 29.8199
      FID (StudioGAN): 26.792
      IS (Our Pipeline): 30.218
      IS (StudioGAN): 32.247
      Inplace ReLU: w
      Total Iters: 1000000.0
      disc_step: 2.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sngan_proj/sngan_imagenet1k_convert-studio-rgb_20210709_111406-877b1130.pth
