blank_issues_enabled: false

contact_links:
  - name: 💬 Forum
    url: https://github.com/open-mmlab/mmgeneration/discussions
    about: Ask general usage questions and discuss with other MMGeneration community members
  - name: 🌐 Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
