Collections:
- Metadata:
    Architecture:
    - StyleGANv2
  Name: StyleGANv2
  Paper:
  - https://openaccess.thecvf.com/content_CVPR_2020/html/Karras_Analyzing_and_Improving_the_Image_Quality_of_StyleGAN_CVPR_2020_paper.html
  README: configs/styleganv2/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_1024_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_1024_b4x8
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      FID50k: 2.8134
      P&R50k: 62.856/49.400
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-ffhq-config-f-official_20210327_171224-bce9310c.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_lsun-car_384x512_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: LSUN
  Name: stylegan2_c2_lsun-car_384x512_b4x8
  Results:
  - Dataset: LSUN
    Metrics:
      Comment: official weight
      FID50k: 5.4316
      P&R50k: 65.986/48.190
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-car-config-f-official_20210327_172340-8cfe053c.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_lsun-horse_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: LSUN
  Name: stylegan2_c2_lsun-horse_256_b4x8_800k
  Results:
  - Dataset: LSUN
    Metrics:
      Comment: official weight
      FID50k: '-'
      P&R50k: '-'
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-horse-config-f-official_20210327_173203-ef3e69ca.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_lsun-church_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: LSUN
  Name: stylegan2_c2_lsun-church_256_b4x8_800k
  Results:
  - Dataset: LSUN
    Metrics:
      Comment: official weight
      FID50k: '-'
      P&R50k: '-'
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-church-config-f-official_20210327_172657-1d42b7d1.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_lsun-cat_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: LSUN
  Name: stylegan2_c2_lsun-cat_256_b4x8_800k
  Results:
  - Dataset: LSUN
    Metrics:
      Comment: official weight
      FID50k: '-'
      P&R50k: '-'
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-cat-config-f-official_20210327_172444-15bc485b.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_256_b4x8_800k
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: our training
      FID50k: 3.992
      P&R50k: 69.012/40.417
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_1024_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_1024_b4x8
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: our training
      FID50k: 2.8185
      P&R50k: 68.236/49.583
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_ffhq_1024_b4x8_20210407_150045-618c9024.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_lsun-car_384x512_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: LSUN
  Name: stylegan2_c2_lsun-car_384x512_b4x8
  Results:
  - Dataset: LSUN
    Metrics:
      Comment: our training
      FID50k: 2.4116
      P&R50k: 66.760/50.576
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_lsun-car_384x512_b4x8_1800k_20210424_160929-fc9072ca.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_256_b4x8_800k
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: baseline
      FID50k: 3.992
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_fp16_partial-GD_PL-no-scaler_ffhq_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_fp16_partial-GD_PL-no-scaler_ffhq_256_b4x8_800k
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: partial layers in fp16
      FID50k: 4.331
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_fp16_partial-GD_PL-no-scaler_ffhq_256_b4x8_800k_20210508_114854-dacbe4c9.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_fp16-globalG-partialD_PL-R1-no-scaler_ffhq_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_fp16-globalG-partialD_PL-R1-no-scaler_ffhq_256_b4x8_800k
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: the whole G in fp16
      FID50k: 4.362
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_fp16-globalG-partialD_PL-R1-no-scaler_ffhq_256_b4x8_800k_20210508_114930-ef8270d4.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_apex_fp16_PL-R1-no-scaler_ffhq_256_b4x8_800k.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_apex_fp16_PL-R1-no-scaler_ffhq_256_b4x8_800k
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: the whole G&D in fp16 + two loss scaler
      FID50k: 4.614
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_apex_fp16_PL-R1-no-scaler_ffhq_256_b4x8_800k_20210508_114701-c2bb8afd.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_1024_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_1024_b4x8
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      FID Version: Tero's StyleGAN
      FID50k: 2.8732
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-ffhq-config-f-official_20210327_171224-bce9310c.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_1024_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_1024_b4x8
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: our training
      FID Version: Tero's StyleGAN
      FID50k: 2.9413
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_ffhq_1024_b4x8_20210407_150045-618c9024.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_1024_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_1024_b4x8
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      FID Version: Our PyTorch
      FID50k: 2.8134
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-ffhq-config-f-official_20210327_171224-bce9310c.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv2/stylegan2_c2_ffhq_1024_b4x8.py
  In Collection: StyleGANv2
  Metadata:
    Training Data: FFHQ
  Name: stylegan2_c2_ffhq_1024_b4x8
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: our training
      FID Version: Our PyTorch
      FID50k: 2.8185
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_ffhq_1024_b4x8_20210407_150045-618c9024.pth
