Collections:
- Metadata:
    Architecture:
    - SAGAN
  Name: SAGAN
  Paper:
  - https://proceedings.mlr.press/v97/zhang19d.html
  README: configs/sagan/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SAGAN
  Metadata:
    Training Data: CIFAR
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      Dataset: CIFAR10
      FID: 10.503
      IS: 9.3217
      Inplace ReLU: w/o
      Iter: 400000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_woReUinplace_20210730_125449_fid-d50568a4_is-04008a9ca.json)'
      Models: SAGAN-32x32-woInplaceReLU Best IS
      Total Batchsize (BZ_PER_GPU \* NGPU): 64x1
      Total Iters*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_woReUinplace_is-iter400000_20210730_125743-4008a9ca.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SAGAN
  Metadata:
    Training Data: CIFAR
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_32_woReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      Dataset: CIFAR10
      FID: 9.4252
      IS: 9.3174
      Inplace ReLU: w/o
      Iter: 480000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_woReUinplace_20210730_125449_fid-d50568a4_is-04008a9ca.json)'
      Models: SAGAN-32x32-woInplaceReLU Best FID
      Total Batchsize (BZ_PER_GPU \* NGPU): 64x1
      Total Iters*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_woReUinplace_fid-iter480000_20210730_125449-d50568a4.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SAGAN
  Metadata:
    Training Data: CIFAR
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      Dataset: CIFAR10
      FID: 11.776
      IS: 9.2286
      Inplace ReLU: w
      Iter: 380000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_wReLUinplace_20210730_125155_fid-cbefb354_is-c77b4d25.json)'
      Models: SAGAN-32x32-wInplaceReLU Best IS
      Total Batchsize (BZ_PER_GPU \* NGPU): 64x1
      Total Iters*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_wReLUinplace_is-iter380000_20210730_124937-c77b4d25.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1.py
  In Collection: SAGAN
  Metadata:
    Training Data: CIFAR
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_32_wReLUinplace_lr-2e-4_ndisc5_cifar10_b64x1
  Results:
  - Dataset: CIFAR
    Metrics:
      Dataset: CIFAR10
      FID: 10.7781
      IS: 9.2061
      Inplace ReLU: w
      Iter: 460000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_wReLUinplace_20210730_125155_fid-cbefb354_is-c77b4d25.json)'
      Models: SAGAN-32x32-wInplaceReLU Best FID
      Total Batchsize (BZ_PER_GPU \* NGPU): 64x1
      Total Iters*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_wReLUinplace_fid-iter460000_20210730_125155-cbefb354.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_128_woReLUinplace_Glr-1e-4_Dlr-4e-4_ndisc1_imagenet1k_b64x4.py
  In Collection: SAGAN
  Metadata:
    Training Data: IMAGENET
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_128_woReLUinplace_Glr-1e-4_Dlr-4e-4_ndisc1_imagenet1k_b64x4
  Results:
  - Dataset: IMAGENET
    Metrics:
      Dataset: ImageNet
      FID: 36.7712
      IS: 31.5938
      Inplace ReLU: w/o
      Iter: 980000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_imagenet1k_128_Glr1e-4_Dlr4e-4_ndisc1_b32x4_woReLUinplace_20210730_163431_fid-d7916963_is-cfbebfc6.json)'
      Models: SAGAN-128x128-woInplaceReLU Best IS
      Total Batchsize (BZ_PER_GPU \* NGPU): 64x4
      Total Iters*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_imagenet1k_128_Glr1e-4_Dlr4e-4_ndisc1_b32x4_woReLUinplace_is-iter980000_20210730_163140-cfbebfc6.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_128_woReLUinplace_Glr-1e-4_Dlr-4e-4_ndisc1_imagenet1k_b64x4.py
  In Collection: SAGAN
  Metadata:
    Training Data: IMAGENET
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_128_woReLUinplace_Glr-1e-4_Dlr-4e-4_ndisc1_imagenet1k_b64x4
  Results:
  - Dataset: IMAGENET
    Metrics:
      Dataset: ImageNet
      FID: 34.7838
      IS: 28.4936
      Inplace ReLU: w/o
      Iter: 950000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_imagenet1k_128_Glr1e-4_Dlr4e-4_ndisc1_b32x4_woReLUinplace_20210730_163431_fid-d7916963_is-cfbebfc6.json)'
      Models: SAGAN-128x128-woInplaceReLU Best FID
      Total Batchsize (BZ_PER_GPU \* NGPU): 64x4
      Total Iters*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_imagenet1k_128_Glr1e-4_Dlr4e-4_ndisc1_b32x4_woReLUinplace_fid-iter950000_20210730_163431-d7916963.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_128_woReLUinplace_noaug_bigGAN_Glr1e-4_Dlr-4e-4_ndisc1_imagenet1k_b32x8.py
  In Collection: SAGAN
  Metadata:
    Training Data: IMAGENET
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_128_woReLUinplace_noaug_bigGAN_Glr1e-4_Dlr-4e-4_ndisc1_imagenet1k_b32x8
  Results:
  - Dataset: IMAGENET
    Metrics:
      Dataset: ImageNet
      FID: 12.8295
      IS: 69.535
      Inplace ReLU: w/o
      Iter: 826000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_128_woReLUinplace_noaug_bigGAN_imagenet1k_b32x8_Glr1e-4_Dlr-4e-4_ndisc1_20210818_210232-3f5686af.json)'
      Models: SAGAN-128x128-BigGAN Schedule Best IS
      Total Batchsize (BZ_PER_GPU \* NGPU): 32x8
      Total Iters*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_128_woReLUinplace_noaug_bigGAN_imagenet1k_b32x8_Glr1e-4_Dlr-4e-4_ndisc1_20210818_210232-3f5686af.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/sagan/sagan_128_woReLUinplace_noaug_bigGAN_Glr1e-4_Dlr-4e-4_ndisc1_imagenet1k_b32x8.py
  In Collection: SAGAN
  Metadata:
    Training Data: IMAGENET
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--sagan--sagan_128_woReLUinplace_noaug_bigGAN_Glr1e-4_Dlr-4e-4_ndisc1_imagenet1k_b32x8
  Results:
  - Dataset: IMAGENET
    Metrics:
      Dataset: ImageNet
      FID: 12.8295
      IS: 69.535
      Inplace ReLU: w/o
      Iter: 826000.0
      Log: '[Log](https://download.openmmlab.com/mmgen/sagan/sagan_128_woReLUinplace_noaug_bigGAN_imagenet1k_b32x8_Glr1e-4_Dlr-4e-4_ndisc1_20210818_210232-3f5686af.json)'
      Models: SAGAN-128x128-BigGAN Schedule Best FID
      Total Batchsize (BZ_PER_GPU \* NGPU): 32x8
      Total Iters*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_128_woReLUinplace_noaug_bigGAN_imagenet1k_b32x8_Glr1e-4_Dlr-4e-4_ndisc1_20210818_210232-3f5686af.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/sagan_32x32.py
  In Collection: SAGAN
  Metadata:
    Training Data: Others
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--_base_--models--sagan_32x32
  Results:
  - Dataset: Others
    Metrics:
      Dataset: CIFAR10
      FID (Our Pipeline): 10.2011
      FID (StudioGAN): 14.009
      IS (Our Pipeline): 9.116
      IS (StudioGAN): 8.68
      Inplace ReLU: w
      Models: SAGAN-32x32 StudioGAN
      Total Iters: 100000.0
      n_disc: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_32_cifar10_convert-studio-rgb_20210730_153321-080da7e2.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/sagan_128x128.py
  In Collection: SAGAN
  Metadata:
    Training Data: Others
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--_base_--models--sagan_128x128
  Results:
  - Dataset: Others
    Metrics:
      Dataset: ImageNet
      FID (Our Pipeline): 40.1162
      FID (StudioGAN): 34.726
      IS (Our Pipeline): 27.367
      IS (StudioGAN): 29.848
      Inplace ReLU: w
      Models: SAGAN0-128x128 StudioGAN
      Total Iters: 1000000.0
      n_disc: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/sagan/sagan_128_imagenet1k_convert-studio-rgb_20210730_153357-eddb0d1d.pth
