Collections:
- Metadata:
    Architecture:
    - PGGAN
  Name: PGGAN
  Paper:
  - https://arxiv.org/abs/1710.10196
  README: configs/pggan/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pggan/pggan_celeba-cropped_128_g8_12Mimgs.py
  In Collection: PGGAN
  Metadata:
    Training Data: CELEBA
  Name: pggan_celeba-cropped_128_g8_12Mimgs
  Results:
  - Dataset: CELEBA
    Metrics:
      Details: celeba-cropped
      MS-SSIM: 0.3023
      SWD(xx,xx,xx,xx/avg): 3.42, 4.04, 4.78, 20.38/8.15
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/pggan/pggan_celeba-cropped_128_g8_20210408_181931-85a2e72c.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pggan/pggan_lsun-bedroom_128_g8_12Mimgs.py
  In Collection: PGGAN
  Metadata:
    Training Data: LSUN
  Name: pggan_lsun-bedroom_128_g8_12Mimgs
  Results:
  - Dataset: LSUN
    Metrics:
      Details: lsun-bedroom
      MS-SSIM: 0.0602
      SWD(xx,xx,xx,xx/avg): 3.5, 2.96, 2.76, 9.65/4.72
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/pggan/pggan_lsun-bedroom_128x128_g8_20210408_182033-5e59f45d.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pggan/pggan_celeba-hq_1024_g8_12Mimg.py
  In Collection: PGGAN
  Metadata:
    Training Data: CELEBA
  Name: pggan_celeba-hq_1024_g8_12Mimg
  Results:
  - Dataset: CELEBA
    Metrics:
      Details: celeba-hq
      MS-SSIM: 0.3379
      SWD(xx,xx,xx,xx/avg): 8.93, 3.98, 3.07, 2.64/4.655
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/pggan/pggan_celeba-hq_1024_g8_20210408_181911-f1ef51c3.pth
