Collections:
- Metadata:
    Architecture:
    - BigGAN
  Name: BigGAN
  Paper:
  - https://openreview.net/forum?id=B1xsqj09Fm
  README: configs/biggan/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_cifar10_32x32_b25x2_500k.py
  In Collection: BigGAN
  Metadata:
    Training Data: CIFAR
  Name: biggan_cifar10
  Results:
  - Dataset: CIFAR
    Metrics:
      Best FID: 9.78
      Best IS: 8.7
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_cifar10_32x32_b25x2_500k_20210728_110906-08b61a44.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_imagenet1k_128x128_b32x8_1500k.py
  In Collection: BigGAN
  Metadata:
    Training Data: IMAGENET
  Name: biggan_imagenet1k
  Results:
  - Dataset: IMAGENET
    Metrics:
      Best FID: 10.02
      Best IS: 86.8
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_b32x8_1449000_20210906_141519-f9128faf.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan_128x128_cvt_BigGAN-PyTorch_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan_cvt
  Results:
  - Dataset: Others
    Metrics:
      FID: 10.1414
      IS: 96.728
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_cvt_BigGAN-PyTorch_rgb_20210730_125223-3e353fef.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_128x128_cvt_hugging-face_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan-deep_128x128
  Results:
  - Dataset: Others
    Metrics:
      FID: 5.9471
      IS: 107.161
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_128x128_cvt_hugging-face_rgb_20210728_111659-099e96f9.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_256x256_cvt_hugging-face_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan-deep_256x256
  Results:
  - Dataset: Others
    Metrics:
      FID: 11.3151
      IS: 135.107
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_256x256_cvt_hugging-face_rgb_20210728_111735-28651569.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_512x512_cvt_hugging-face_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan-deep_512x512
  Results:
  - Dataset: Others
    Metrics:
      FID: 16.8728
      IS: 124.368
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_512x512_cvt_hugging-face_rgb_20210728_112346-a42585f2.pth
