Collections:
- Metadata:
    Architecture:
    - BigGAN
  Name: BigGAN
  Paper:
  - https://openreview.net/forum?id=B1xsqj09Fm
  README: configs/biggan/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_cifar10_32x32_b25x2_500k.py
  In Collection: README
  Metadata:
    Training Data: CIFAR
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--biggan--biggan_cifar10_32x32_b25x2_500k
  Results:
  - Dataset: CIFAR
    Metrics:
      Best FID (Iter): 9.78(390000)
      Best IS (Iter): 8.70(390000)
      Dataset: CIFAR10
      Models: BigGAN 32x32
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_cifar10_32x32_b25x2_500k_20210728_110906-08b61a44.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_imagenet1k_128x128_b32x8_1500k.py
  In Collection: README
  Metadata:
    Training Data: IMAGENET
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--biggan--biggan_imagenet1k_128x128_b32x8_1500k
  Results:
  - Dataset: IMAGENET
    Metrics:
      Best FID (Iter): 10.02(1449000)
      Best IS (Iter): 86.8(1449000)
      Dataset: ImageNet1k
      Models: BigGAN 128x128
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_b32x8_1449000_20210906_141519-f9128faf.pth?versionId=CAEQMhiBgIDn.ILn3RciIDFiMTZhZjIxYzA2MjQxMTJiMDQzZjQyNWQ5YTVkY2Jl
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan_128x128_cvt_BigGAN-PyTorch_rgb.py
  In Collection: README
  Metadata:
    Training Data: Others
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--_base_--models--biggan--biggan_128x128_cvt_BigGAN-PyTorch_rgb
  Results:
  - Dataset: Others
    Metrics:
      Dataset: ImageNet1k
      FID: 10.1414
      IS: 96.728
      Models: BigGAN 128x128
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_cvt_BigGAN-PyTorch_rgb_20210730_125223-3e353fef.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_128x128_cvt_hugging-face_rgb.py
  In Collection: README
  Metadata:
    Training Data: Others
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--_base_--models--biggan--biggan-deep_128x128_cvt_hugging-face_rgb
  Results:
  - Dataset: Others
    Metrics:
      Dataset: ImageNet1k
      FID: 5.9471
      IS: 107.161
      Models: BigGAN-Deep 128x128
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_128x128_cvt_hugging-face_rgb_20210728_111659-099e96f9.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_256x256_cvt_hugging-face_rgb.py
  In Collection: README
  Metadata:
    Training Data: Others
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--_base_--models--biggan--biggan-deep_256x256_cvt_hugging-face_rgb
  Results:
  - Dataset: Others
    Metrics:
      Dataset: ImageNet1k
      FID: 11.3151
      IS: 135.107
      Models: BigGAN-Deep 256x256
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_256x256_cvt_hugging-face_rgb_20210728_111735-28651569.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_512x512_cvt_hugging-face_rgb.py
  In Collection: README
  Metadata:
    Training Data: Others
  Name: https:----github.com--open-mmlab--mmgeneration--blob--master--_base_--models--biggan--biggan-deep_512x512_cvt_hugging-face_rgb
  Results:
  - Dataset: Others
    Metrics:
      Dataset: ImageNet1k
      FID: 16.8728
      IS: 124.368
      Models: BigGAN-Deep 512x512
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_512x512_cvt_hugging-face_rgb_20210728_112346-a42585f2.pth
