Collections:
- Metadata:
    Architecture:
    - BigGAN
  Name: BigGAN
  Paper:
  - https://openreview.net/forum?id=B1xsqj09Fm
  README: configs/biggan/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_cifar10_32x32_b25x2_500k.py
  In Collection: BigGAN
  Metadata:
    Training Data: CIFAR
  Name: biggan_cifar10_32x32_b25x2_500k
  Results:
  - Dataset: CIFAR
    Metrics:
      FID: 9.78
      IS: 8.7
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_cifar10_32x32_b25x2_500k_20210728_110906-08b61a44.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_ajbrock-sn_imagenet1k_128x128_b32x8_1500k.py
  In Collection: BigGAN
  Metadata:
    Training Data: IMAGENET
  Name: biggan_ajbrock-sn_imagenet1k_128x128_b32x8_1500k
  Results:
  - Dataset: IMAGENET
    Metrics:
      FID: 8.69
      IS: 101.15
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_b32x8_best_fid_iter_1232000_20211111_122548-5315b13d.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/biggan/biggan_ajbrock-sn_imagenet1k_128x128_b32x8_1500k.py
  In Collection: BigGAN
  Metadata:
    Training Data: IMAGENET
  Name: biggan_ajbrock-sn_imagenet1k_128x128_b32x8_1500k
  Results:
  - Dataset: IMAGENET
    Metrics:
      FID: 13.51
      IS: 129.07
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_b32x8_best_is_iter_1328000_20211111_122911-28c688bc.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan_128x128_cvt_BigGAN-PyTorch_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan_128x128_cvt_BigGAN-PyTorch_rgb
  Results:
  - Dataset: Others
    Metrics:
      FID: 10.1414
      IS: 96.728
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan_imagenet1k_128x128_cvt_BigGAN-PyTorch_rgb_20210730_125223-3e353fef.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_128x128_cvt_hugging-face_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan-deep_128x128_cvt_hugging-face_rgb
  Results:
  - Dataset: Others
    Metrics:
      FID: 5.9471
      IS: 107.161
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_128x128_cvt_hugging-face_rgb_20210728_111659-099e96f9.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_256x256_cvt_hugging-face_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan-deep_256x256_cvt_hugging-face_rgb
  Results:
  - Dataset: Others
    Metrics:
      FID: 11.3151
      IS: 135.107
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_256x256_cvt_hugging-face_rgb_20210728_111735-28651569.pth
- Config: https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/models/biggan/biggan-deep_512x512_cvt_hugging-face_rgb.py
  In Collection: BigGAN
  Metadata:
    Training Data: Others
  Name: biggan-deep_512x512_cvt_hugging-face_rgb
  Results:
  - Dataset: Others
    Metrics:
      FID: 16.8728
      IS: 124.368
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmgen/biggan/biggan-deep_imagenet1k_512x512_cvt_hugging-face_rgb_20210728_112346-a42585f2.pth
