Collections:
- Metadata:
    Architecture:
    - Pix2Pix
  Name: Pix2Pix
  Paper:
  - https://openaccess.thecvf.com/content_cvpr_2017/html/Isola_Image-To-Image_Translation_With_CVPR_2017_paper.html
  README: configs/pix2pix/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pix2pix/pix2pix_vanilla_unet_bn_1x1_80k_facades.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: FACADES
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--pix2pix--pix2pix_vanilla_unet_bn_1x1_80k_facades
  Results:
  - Dataset: FACADES
    Metrics:
      Dataset: facades
      FID: 124.9773
      IS: 1.62
      Models: Ours
    Task: Image2Image Translation
  Weights: https://download.openmmlab.com/mmgen/pix2pix/refactor/pix2pix_vanilla_unet_bn_1x1_80k_facades_20210902_170442-c0958d50.pth?versionId=CAEQMhiBgICb8fTj3RciIGU2NmViM2QyYzJkODQ0MDBhYTFhMGE2YzNmMTA0ODk3
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pix2pix/pix2pix_vanilla_unet_bn_1x1_220k_aerial2maps.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: MAPS
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--pix2pix--pix2pix_vanilla_unet_bn_1x1_220k_aerial2maps
  Results:
  - Dataset: MAPS
    Metrics:
      Dataset: aerial2maps
      FID: 122.5856
      IS: 3.137
      Models: Ours
    Task: Image2Image Translation
  Weights: https://download.openmmlab.com/mmgen/pix2pix/refactor/pix2pix_vanilla_unet_bn_a2b_1x1_219200_maps_convert-bgr_20210902_170729-59a31517.pth?versionId=CAEQMhiBgICH9vTj3RciIDdiNGRmYTNlZjhlMjQ0ODc4OTJiOGEzMjY0YTJlZmQ5
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pix2pix/pix2pix_vanilla_unet_bn_1x1_220k_maps2aerial.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: MAPS
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--pix2pix--pix2pix_vanilla_unet_bn_1x1_220k_maps2aerial
  Results:
  - Dataset: MAPS
    Metrics:
      Dataset: maps2aerial
      FID: 88.4635
      IS: 3.31
      Models: Ours
    Task: Image2Image Translation
  Weights: https://download.openmmlab.com/mmgen/pix2pix/refactor/pix2pix_vanilla_unet_bn_b2a_1x1_219200_maps_convert-bgr_20210902_170814-6d2eac4a.pth?versionId=CAEQMhiBgMC08PTj3RciIGE4ODVkZWU0MTYyMTQ0MWJhZjE0YThmY2M2NDJmZjNi
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/pix2pix/pix2pix_vanilla_unet_bn_wo_jitter_flip_1x4_190k_edges2shoes.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: EDGES2SHOES
  Name: https:----github.com--open-mmlab--mmgeneration--tree--master--pix2pix--pix2pix_vanilla_unet_bn_wo_jitter_flip_1x4_190k_edges2shoes
  Results:
  - Dataset: EDGES2SHOES
    Metrics:
      Dataset: edges2shoes
      FID: 84.375
      IS: 2.815
      Models: Ours
    Task: Image2Image Translation
  Weights: https://download.openmmlab.com/mmgen/pix2pix/refactor/pix2pix_vanilla_unet_bn_wo_jitter_flip_1x4_186840_edges2shoes_convert-bgr_20210902_170902-0c828552.pth?versionId=CAEQMhiBgIC57vTj3RciIGZlNmQ4ZDJhN2E1MDQ5ZmJiOWJmYTY5MDg1ZTc0N2Vi
