Collections:
- Metadata:
    Architecture:
    - WGAN-GP
  Name: WGAN-GP
  Paper:
  - https://arxiv.org/abs/1704.00028
  README: configs/wgan-gp/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/wgan-gp/wgangp_GN_celeba-cropped_128_b64x1_160kiter.py
  In Collection: WGAN-GP
  Metadata:
    Training Data: CELEBA
  Name: wgangp_GN_celeba-cropped_128_b64x1_160kiter
  Results:
  - Dataset: CELEBA
    Metrics:
      Details: GN
      MS-SSIM: 0.2601
      SWD: 5.87, 9.76, 9.43, 18.84/10.97
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/wgangp/wgangp_GN_celeba-cropped_128_b64x1_160k_20210408_170611-f8a99336.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/wgan-gp/wgangp_GN_GP-50_lsun-bedroom_128_b64x1_160kiter.py
  In Collection: WGAN-GP
  Metadata:
    Training Data: LSUN
  Name: wgangp_GN_GP-50_lsun-bedroom_128_b64x1_160kiter
  Results:
  - Dataset: LSUN
    Metrics:
      Details: GN, GP-lambda = 50
      MS-SSIM: 0.059
      SWD: 11.7, 7.87, 9.82, 25.36/13.69
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/wgangp/wgangp_GN_GP-50_lsun-bedroom_128_b64x1_130k_20210408_170509-56f2a37c.pth
